name: 'open and merge a PR to a branch'
description: 'Merges a PR to a given branch'
inputs:
  GH_PAT:
    description: 'github token with permissions to run this actions'
    required: true
  target-branch:
    description: 'branch on which source PR needs to be merged'
    required: true
  source-branch:
    description: "Name of the branch that needs to be merged."
    required: true
  title:
    description: "Title of the PR"
    required: true
  pr-body:
    description: "body of the PR"
    required: true
  merge-pr:
    description: should PR be merged. 
    required: true
    default: "true"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: setup github token
      shell: bash
      run: |
        echo "GH_TOKEN=${{ inputs.GH_PAT }}" >> $GITHUB_ENV
        
    - name: create a PR
      id: create-pr
      shell: bash
      run: |
        echo "PR_URL=$(gh pr create -B '${{ inputs.target-branch }}' -b '${{ inputs.pr-body }}' -H '${{ inputs.source-branch }}' -t '${{ inputs.title }}')" >> $GITHUB_ENV

    - name: merge PR
      id: merge-pr
      if: ${{ inputs.merge-pr == 'true' }} 
      shell: bash
      run: |
        echo "merging ${{ env.PR_URL }}"
        gh pr merge -m ${{ env.PR_URL }}