name: Auto Merge Dependabot
description: Auto approve and merge PRs by Dependabot

# Trigger the workflow on pull request
inputs:
  github-pat:
    description: "GitHub PAT for the ci-bot"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ inputs.github-pat }}
